#!/usr/bin/bash

sudo pacman -Syu
sudo pacman -S --needed --noconfirm alacritty git neovim firefox tmux obsidian
sudo pacman -S --needed --noconfirm hyprland waybar xdg-desktop-portal-hyprland qt5-wayland qt6-wayland
sudo pacman -S --needed --noconfirm dunst dolphin wofi polkit-kde-agent grim slurp
sudo pacman -S --needed --noconfirm go fzf fastfetch brightnessctl wl-clipboard
