#!/usr/bin/bash

sudo pacman -Syu
sudo pacman -S --needed --noconfirm alacritty git neovim firefox tmux
sudo pacman -S --needed --noconfirm hyprland waybar xdg-desktop-portal-hyprland qt5-wayland qt6-wayland
sudo pacman -S --needed --noconfirm dunst dolphin wofi polkit-kde-agent grim slurp
sudo pacman -S --needed --noconfirm ttf-mononoki-nerd ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols ttf-font-awesome
sudo pacman -S --needed --noconfirm go fzf fastfetch brightnessctl wl-clipboard
