#!/usr/bin/bash

sudo pacman -Syu
sudo pacman -S --noconfirm --needed alacritty git neovim firefox
sudo pacman -S --noconfirm --needed go tmux fzf
sudo pacman -S --noconfirm --needed waybar ttf-font-awesome
